# Generated by Django 5.0 on 2023-12-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profinity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestones',
            new_name='Milestone',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
